package Form;

import java.awt.Color;
import javaswingdev.drawer.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Tri Dung
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    DrawerController drawer;

    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(3);
        setMenu();
    }

    void setMenu() {
        drawer = Drawer.newDrawer(this)
                .header(new JLabel("aaaa"))
                .separator(2, Color.black)
                .enableScroll(true)
                .duration(600)
                .addChild(new DrawerItem("Item Name").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .addChild(new DrawerItem("Item Name").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .addChild(new DrawerItem("Item Name").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .addChild(new DrawerItem("Item Name").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .addChild(new DrawerItem("Item Name").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .addChild(new DrawerItem("Item Name").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .addFooter(new DrawerItem("Exit").icon(new ImageIcon("src\\images\\Icons8-Ios7-Food-Bread.32.png")).build())
                .build();
    }

    void openMenu() {
        if (drawer.isShow()) {
            drawer.hide();
        } else {
            drawer.show();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OpenMenubtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OpenMenubtn.setText("|||");
        OpenMenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenMenubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(636, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OpenMenubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenMenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenubtnActionPerformed
        // TODO add your handling code here:
        openMenu();
    }//GEN-LAST:event_OpenMenubtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OpenMenubtn;
    // End of variables declaration//GEN-END:variables
}
